language: java

jdk:
  - oraclejdk8

script:
    - cp ASCIIGenome build/libs/
    - cd src/test/java
    - bash integration_test.sh ../../../build/libs/ASCIIGenome

after_success:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)
