language: java

jdk:
  - openjdk8

script:
    - ./gradlew test jacocoTestReport || true
    - bash <(curl -s https://codecov.io/bash) || true
    - cp ASCIIGenome build/libs/
    - cd src/test/java
    - bash integration_test.sh ../../../build/libs/ASCIIGenome
